[workspace]

members = [
    "src/systems/a320_systems",
    "src/systems/a320_systems_wasm",
    "src/systems/systems",
    "src/systems/systems_wasm",
    "src/systems/a320_hydraulic_simulation_graphs",
]

[profile.release]
lto = true
